export const SETUSER = 'SETUSER';
export const SETVOICESTATE = 'SETVOICESTATE';
export const SETSOCKETINSTANCE = 'SETSOCKETINSTANCE';
export const SETREFRESHSTATE = 'SETREFRESHSTATE';
export const SETNOTIFICATIONID = 'SETNOTIFICATIONID';
export const SETMESSAGECOUNT = 'SETMESSAGECOUNT';